---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
  run_list:
  - recipe[yum::epel]
- name: centos-5.8
  driver_config:
    box: opscode-centos-5.8
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.8.box
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[graphite]
  attributes: {}
- name: ssl
  run_list:
  - recipe[graphite_test::ssl]
  - recipe[graphite]
  attributes: {
    "graphite": {
      "ssl": {
        "enabled": true
      },
      "listen_port": "443"
    }
  }
- name: uwsgi
  run_list:
  - recipe[graphite]
  attributes: {
    "graphite": {
      "listen_port": "8080",
      "web_server": "uswsgi"
    }
  }
- name: carbon-relay
  run_list:
  - recipe[graphite]
  - recipe[graphite::carbon_relay]
  attributes: {
    "graphite": {
      "carbon": {
        "relay": {
          "destinations": [ "127.0.0.1:2003:a" ]
        },
      },
      "relay_rules": [
        {
          "name": "example",
          "pattern": "^mydata\\.foo\\..+",
          "destinations": [ "127.0.0.1:2003:a" ],
          "default": true
        }
      ]
    }
  }
